### ISSUE TITLE
import ansible cluster to tiup, user-defined port param in group_vars didn't be imported

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tiup#1034]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
    1. install tidb 3.0.8 cluster with ansible
    2. import this cluster to tiup

2. What did you expect to see?

the params with imported cluster is same with it in ansible

3. What did you see instead?

pump and drainer 's port changed to default value, don't use used defined in tidb-ansible/group_vars directory.

4. What version of TiUP are you using (`tiup --version`)?

─$ tiup --version
v1.3.0 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: edb12b8

**Comment by seiya-annie** [comment]
the workaround is： add port param in inventory.ini file, like 
xx.xx.xx.xx pump_port=32250

**Comment by 9547** [comment]
Which file do you place the `pump_port` and `drainer_port`, the tidb-ansible places those variables inside `group_vars/all.yml`, not inside `group_vars/pump_servers.yml` 

ref [group_vars/all.yml#L40-L47](https://github.com/pingcap/tidb-ansible/blob/d6b6390eaaf2bbc6b72d70b6caf414b95e882dc5/group_vars/all.yml#L41-L47)

```yml
# pump
pump_port: 8250
pump_data_dir: "{{ deploy_dir }}/data.pump"
pump_log_dir: "{{ deploy_dir }}/log"
pump_cert_dir: "{{ deploy_dir }}/conf/ssl"

# drainer
drainer_port: 8249
```

So if you place those variables inside `group_vars/pump_servers.yml`, then these variables are not going to work.
