### ISSUE TITLE
tiup deploy should use given address by default instead of 0.0.0.0

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tiup#1082]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Using tiup to deploy a cluster.

2. What did you expect to see?
Everything works correctly.

3. What did you see instead?
There are warnings in logs:
```
[2021/01/20 16:34:38.757 +08:00] [WARN] [mod.rs:520] ["failed to register addr to pd"] [body=Body(Streaming)] ["status code"=400]
[2021/01/20 16:34:38.781 +08:00] [WARN] [mod.rs:520] ["failed to register addr to pd"] [body=Body(Streaming)] ["status code"=400]
[2021/01/20 16:34:38.799 +08:00] [WARN] [mod.rs:520] ["failed to register addr to pd"] [body=Body(Streaming)] ["status code"=400]
[2021/01/20 16:34:38.820 +08:00] [WARN] [mod.rs:520] ["failed to register addr to pd"] [body=Body(Streaming)] ["status code"=400]
[2021/01/20 16:34:38.820 +08:00] [WARN] [mod.rs:530] ["failed to register addr to pd after 5 tries"]
```

That's because tiup use 0.0.0.0 as status address for all nodes, and same address can't be registered multiple times. Actually I have never configure it to use 0.0.0.0, what I set to host is IP like 127.0.0.1. Tiup should utilize the IP instead.

4. What version of TiUP are you using (`tiup --version`)?
```
v1.3.1 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: d51bd0c
```

**Comment by lucklove** [comment]
I deployed a cluster with the following config (with tidb v4.0.9), this issue not reproduced:

```yaml
tidb_servers:
  - host: 172.16.5.140

pd_servers:
  - host: 172.16.5.140
    name: pd-1

tikv_servers:
  - host: 172.16.5.140
  - host: 172.16.5.139
  - host: 172.16.5.134

monitoring_servers:
  - host: 172.16.5.140

grafana_servers:
  - host: 172.16.5.140

alertmanager_servers:
  - host: 172.16.5.140
```

I notice that the generated tikv script is:

```sh
#!/bin/bash
set -e

# WARNING: This file was auto-generated. Do not edit!
#          All your edit might be overwritten!
cd "/home/tidb/deploy/tikv-20160" || exit 1

echo -n 'sync ... '
stat=$(time sync || sync)
echo ok
echo $stat
exec bin/tikv-server \
    --addr "0.0.0.0:20160" \
    --advertise-addr "172.16.5.140:20160" \
    --status-addr "0.0.0.0:20180" \
    --advertise-status-addr "172.16.5.140:20180" \
    --pd "172.16.5.140:2379" \
    --data-dir "/home/tidb/deploy/tikv-20160/data" \
    --config conf/tikv.toml \
    --log-file "/home/tidb/deploy/tikv-20160/log/tikv.log" 2>> "/home/tidb/deploy/tikv-20160/log/tikv_stderr.log"
```

Only `--addr` and `--status-addr` use `0.0.0.0`, but I found that these address is [0.0.0.0](https://github.com/pingcap/tidb-ansible/blob/3365381314949cfef9324b5b4664432443bb652b/roles/tikv/templates/run_tikv_binary.sh.j2#L32) from the ansible's time.

So can you have a check if there is something wrong with the tikv version you used?
