### ISSUE TITLE
tiup cluster check report fail unexpectly

### ISSUE THREAD

**Issue by cosven** [pingcap/tiup#1140]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I run this command
```
tiup cluster check testing --cluster
```

2. What did you expect to see?
No Fail.
I do not deploy tikv on the `172.16.4.84` node. So I think it's ok that `mount point / does not have 'nodelalloc' option set`. Here is a part of my topology.yaml that is related to `172.16.4.84`.
```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/home/testing/deploy"  # for monitor components
pd_servers:
  - host: 172.16.4.84
    ssh_port: 22
    client_port: 2379
    peer_port: 2380
    deploy_dir: "/data1/testing/pd-2379"
tidb_servers:
  - host: 172.16.4.84
    ssh_port: 22
    port: 4000
    status_port: 10080
    deploy_dir: "/data1/testing/tidb-4000"
    numa_node: "0"
monitoring_servers:
  - host: 172.16.4.84
    port: 9090
grafana_servers:
  - host: 172.16.4.84
    port: 3000
alertmanager_servers:
  - host: 172.16.4.84
    web_port: 9093
```

3. What did you see instead?
```
172.16.4.84  disk            Fail    mount point / does not have 'nodelalloc' option set
172.16.4.84  disk            Warn    mount point / does not have 'noatime' option set
172.16.4.84  disk            Fail    mount point / does not have 'nodelalloc' option set
```

4. What version of TiUP are you using (`tiup --version`)?

```
[root@localhost data-testing]# tiup --version
v1.3.2 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: 2d88460
[root@localhost data-testing]# tiup cluster --version
Starting component `cluster`: /root/.tiup/components/cluster/v1.3.2/tiup-cluster --version
tiup version v1.3.2 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: 2d88460
```
