### ISSUE TITLE
cluster deployed by tiup doesn't collect node_exporter metrics for tiflash node

### ISSUE THREAD

**Issue by lidezhu** [pingcap/tiup#1165]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Deploy a cluster with tiflash node. And then check the node_exporter info of tiflash in grafana and the config file of prometheus.

2. What did you expect to see?
No tiflash node_exporter info is provided. And the config file of prometheus doesn't contain the node exporter info for tiflash node.

3. What did you see instead?
Tiflash node_exporter info is provided. And the config file of prometheus contains the node exporter info for tiflash node.

4. What version of TiUP are you using (`tiup --version`)?
v1.3.2 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: 2d88460

**Comment by 9547** [comment]
Could you please provide the topology.yaml ?

**Comment by lidezhu** [comment]
`global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/data1/tidb-deploy"
  data_dir: "/data1/tidb-data"

monitored:
  node_exporter_port: 9199
  blackbox_exporter_port: 9195

server_configs:
  tidb:
    log.slow-threshold: 300
    binlog.enable: false
    binlog.ignore-error: false
  tikv:
    readpool.storage.use-unified-pool: false
    readpool.coprocessor.use-unified-pool: true
  pd:
    schedule.leader-schedule-limit: 4
    schedule.region-schedule-limit: 2048
    schedule.replica-schedule-limit: 64
    replication.enable-placement-rules: true
  tiflash:
    path_realtime_mode: false
    logger.level: "debug"

pd_servers:
  - host: 172.16.5.59
    client_port: 8379
    peer_port: 8380
    config:
        replication.max-replicas: 1

tidb_servers:
  - host: 172.16.5.59
    port: 5050
    status_port: 10088
  - host: 172.16.5.59
    port: 5150
    status_port: 11088

tikv_servers:
  - host: 172.16.5.59
    port: 20360
    status_port: 20380

tiflash_servers:
  - host: 172.16.5.82
    tcp_port: 9089
    http_port: 9129
    flash_service_port: 7940
    flash_proxy_port: 21270
    flash_proxy_status_port: 20592
    metrics_port: 8344

monitoring_servers:
  - host: 172.16.5.59
    port: 9099

grafana_servers:
  - host: 172.16.5.59
    port: 3333`

**Comment by 9547** [comment]
@lidezhu I've deployed a similar cluster with your topology, but I didn't see anything wrong. The Prometheus's config contains the node exporter. Could you please describe more information ?

**Comment by lidezhu** [comment]
What do you mean by "The Prometheus's config contains the node exporter."? Does the Prometheus contains the node exporter info for tiflash node? Does tiflash deploy on a seperate node with no other tidb component?

**Comment by 9547** [comment]
> Does the Prometheus contains the node exporter info for tiflash node?

Yes

> Does tiflash deploy on a seperate node with no other tidb component?

Yes

And my _topology.yaml_ like below:

```yaml
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/data1/tidb-deploy"
  data_dir: "/data1/tidb-data"

monitored:
  node_exporter_port: 9199
  blackbox_exporter_port: 9195

server_configs:
  tidb:
    log.slow-threshold: 300
    binlog.enable: false
    binlog.ignore-error: false
  tikv:
    readpool.storage.use-unified-pool: false
    readpool.coprocessor.use-unified-pool: true
  pd:
    schedule.leader-schedule-limit: 4
    schedule.region-schedule-limit: 2048
    schedule.replica-schedule-limit: 64
    replication.enable-placement-rules: true
  tiflash:
    path_realtime_mode: false
    logger.level: "debug"

pd_servers:
  - host: n1
    client_port: 8379
    peer_port: 8380
    config:
      replication.max-replicas: 1

tidb_servers:
  - host: n1
    port: 5050
    status_port: 10088
  - host: n1
    port: 5150
    status_port: 11088

tikv_servers:
  - host: n1
    port: 20360
    status_port: 20380

tiflash_servers:
  - host: n2
    tcp_port: 9089
    http_port: 9129
    flash_service_port: 7940
    flash_proxy_port: 21270
    flash_proxy_status_port: 20592
    metrics_port: 8344

monitoring_servers:
  - host: n1
    port: 9099

grafana_servers:
  - host: n1
    port: 3333
```

The `cluster display` show as below:

![image](https://user-images.githubusercontent.com/29431502/110505510-2d6a6b00-8139-11eb-9361-dc2ae5101976.png)

and the `/data1/tidb-deploy/prometheus-9099/conf/prometheus.yaml` contains the node_exporter 
![image](https://user-images.githubusercontent.com/29431502/110505421-19bf0480-8139-11eb-881d-bebde27c4e47.png)
