### ISSUE TITLE
Bug: cluster failed to deploy using tiup v1.3.3

### ISSUE THREAD

**Issue by mahjonp** [pingcap/tiup#1186]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

tiup cluster deploy test-cluster nightly topology.yaml -i ~/insecure_key

```yaml
global:
  user: root
  ssh_port: 22
  ssh_type: builtin
  deploy_dir: /disk1/deploy
  data_dir: /disk1/data
  os: linux
  arch: amd64
monitored:
  node_exporter_port: 9100
  blackbox_exporter_port: 9115
tidb_servers:
- host: 10.0.2.44
  ssh_port: 22
  port: 4000
  status_port: 10080
tikv_servers:
- host: 10.0.2.46
  ssh_port: 22
  port: 20160
  status_port: 20180
- host: 10.0.2.47
  ssh_port: 22
  port: 20160
  status_port: 20180
- host: 10.0.2.55
  ssh_port: 22
  port: 20160
  status_port: 20180
tiflash_servers: []
pd_servers:
- host: 10.0.2.43
  ssh_port: 22
  name: ""
  client_port: 2379
  peer_port: 2380
monitoring_servers:
- host: 10.0.2.42
  ssh_port: 22
  port: 9090
grafana_servers:
- host: 10.0.2.42
  ssh_port: 22
  port: 3000
  username: admin
  password: admin
```

2. What did you expect to see?

OK

3. What did you see instead?

```log
+ Copy files
  - Copy pd -> 10.0.2.43 ... Done
  - Copy tikv -> 10.0.2.46 ... Done
  - Copy tikv -> 10.0.2.47 ... Done
  - Copy tikv -> 10.0.2.55 ... Done
  - Copy tidb -> 10.0.2.44 ... Done
  - Copy prometheus -> 10.0.2.42 ... Error
  - Copy grafana -> 10.0.2.42 ... Done
  - Copy node_exporter -> 10.0.2.47 ... Done
  - Copy node_exporter -> 10.0.2.55 ... Done
  - Copy node_exporter -> 10.0.2.44 ... Done
  - Copy node_exporter -> 10.0.2.42 ... Done
  - Copy node_exporter -> 10.0.2.43 ... Done
  - Copy node_exporter -> 10.0.2.46 ... Done
  - Copy blackbox_exporter -> 10.0.2.46 ... Done
  - Copy blackbox_exporter -> 10.0.2.47 ... Done
  - Copy blackbox_exporter -> 10.0.2.55 ... Done
  - Copy blackbox_exporter -> 10.0.2.44 ... Done
  - Copy blackbox_exporter -> 10.0.2.42 ... Done
  - Copy blackbox_exporter -> 10.0.2.43 ... Done

Error: init config failed: 10.0.2.42:9090: template: Prometheus:45: unexpected {{end}}

Verbose debug logs has been written to /root/.tiup/logs/tiup-cluster-debug-2021-03-05-10-19-59.log.

```

4. What version of TiUP are you using (`tiup --version`)?

[root@35b34352c428 ~]# tiup --version
v1.3.2 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: 2d88460
