### ISSUE TITLE
cdc: support config file for ticdc server

### ISSUE THREAD

**Issue by leoppro** [pingcap/tiup#1205]
## Feature Request

**Describe the feature you'd like:**

The TiCDC support sever config file from 5.0.0 (PR: https://github.com/pingcap/ticdc/pull/1493), and I hope that TiUP can support manage the ticdc with config file.

There are two components need to modify:

#### playground

add a `--ticdc.config` flag to set the ticdc server config file

#### cluster 

the user can edit the cdc config in cluster topology config file like this:

```
server_configs:
  tidb:
    log.slow-threshold: 300
  tikv:
    # xxxxx
  ticdc:
    tz: "UTC"
    gc-ttl: 60000
```

and deploy a ticdc cluster with config.

**Comment by 9547** [comment]
@leoppro  In the current implementation, the TiCDC's configuration name in `server_configs` is `cdc`, so you can use it directly like below:

```yaml
server_configs:
  tidb:
    log.slow-threshold: 300
  tikv:
    # xxxxx
  cdc:
    tz: "UTC"
    gc-ttl: 60000
```
