### ISSUE TITLE
Make advertise urls configurable

### ISSUE THREAD

**Issue by Connor1996** [pingcap/tiup#1218]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiKV and PD have some `advertise-xxx-urls` to indicate the remote accessible address for clients under NAT environment. We are expected to set it individually, but tiup generates the run script with fixed advertised address(host:ip) 
https://docs.pingcap.com/zh/tidb/stable/command-line-flags-for-tikv-configuration#--advertise-addr and https://docs.pingcap.com/zh/tidb/stable/command-line-flags-for-pd-configuration#--advertise-client-urls 

**Describe the feature you'd like:**

In yaml file, add config for these `advertise-xxx-urls` and set the corresponding field of the run script(if one is not set, use default value as before).
```
tikv_servers:
   - host: xxxxxx
     port: xxxxx
     advertise_addr: xxxx
     advertise_status_addr: xxxx
pd_servers:
    - host: xxxx
      port: xxxx
      advertise_client_urls: xxx
      advertise_peer_urls: xxx
```

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

None
