### ISSUE TITLE
tiup cluster custom recursion ERROR

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tiup#1239]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

2. What did you expect to see?

```
global:
  custom:
    tidb_spec: &tidb_spec
      port: 4444
      deploy_dir: "/home/uuu/deploy/tidb-1234"
      config:
        token-limit: 4000


tidb_servers:
  - <<: *tidb_spec
    host: 172.8.8.8
    port: 4445
    config:
      token-limit: 4333

```

```
Error: Failed to parse topology file custom4.yaml (topology.parse_failed)
  caused by: yaml: unmarshal errors:
  line 32: key "token-limit" already set in map
```

3. What did you see instead?

```
--- 
global: 
  custom: 
    tidb_spec: 
      config: 
        token-limit: 4000
      deploy_dir: /home/uuu/deploy/tidb-1234
      port: 4444
tidb_servers: 
  - 
    config: 
      token-limit: 4333
    deploy_dir: /home/uuu/deploy/tidb-1234
    host: "172.8.8.8"
    port: 4445
```

4. What version of TiUP are you using (`tiup --version`)?

```
[root@CentOS76_VM bin]# tiup -v
tiup version 1.3.4 tiup
Go Version: go1.16
Git Ref: fix-replay
GitHash: f04decb
[root@CentOS76_VM bin]# tiup cluster -v
tiup version 1.3.4 tiup
Go Version: go1.16
Git Ref: fix-replay
GitHash: f04decb

```
