### ISSUE TITLE
tiup-dm import failed after upgrade to 1.4.0

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tiup#1266]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

deploy dm v1.0

inventory.ini 
```
## DM modules
[dm_master_servers]
dm_master ansible_host=172.28.0.101

[dm_worker_servers]
dm-worker1 ansible_host=172.28.0.111  server_id=101 source_id="mysql-replica-01" mysql_host=mysql1 mysql_user=root mysql_password='' mysql_port=3306

dm-worker2 ansible_host=172.28.0.112  server_id=101 source_id="mysql-replica-02" mysql_host=mysql2 mysql_user=root mysql_password='' mysql_port=3306

## Monitoring modules
[prometheus_servers]
prometheus ansible_host=172.28.0.121

[grafana_servers]
grafana ansible_host=172.28.0.121

[alertmanager_servers]
alertmanager ansible_host=172.28.0.121

## Global variables
[all:vars]
cluster_name = dm-v1

ansible_user = tidb

dm_version = v1.0.6

deploy_dir = /home/tidb/deploy

grafana_admin_user = "admin"
grafana_admin_password = "admin"
```

tiup dm import --yes --dir=/home/tidb/dm-ansible --cluster-version v2.0.1
2. What did you expect to see?
upgrade successfully

3. What did you see instead?
```
## DM modules
[dm_master_servers]
dm_master ansible_host=172.28.0.101

[dm_worker_servers]
dm-worker1 ansible_host=172.28.0.111  server_id=101 source_id="mysql-replica-01" mysql_host=mysql1 mysql_user=root mysql_password='' mysql_port=3306

dm-worker2 ansible_host=172.28.0.112  server_id=101 source_id="mysql-replica-02" mysql_host=mysql2 mysql_user=root mysql_password='' mysql_port=3306

## Monitoring modules
[prometheus_servers]
prometheus ansible_host=172.28.0.121

[grafana_servers]
grafana ansible_host=172.28.0.121

[alertmanager_servers]
alertmanager ansible_host=172.28.0.121

## Global variables
[all:vars]
cluster_name = dm-v1

ansible_user = tidb

dm_version = v1.0.6

deploy_dir = /home/tidb/deploy

grafana_admin_user = "admin"
grafana_admin_password = "admin"
```

4. What version of TiUP are you using (`tiup --version`)?

```
1.4.0 tiup
Go Version: go1.16.2
Git Ref: v1.4.0
GitHash: eb335e6ad9d0dc19d1c43db422cd409d62bc3cea
```

**Comment by AstroProfundis** [comment]
Hello, did you try the same operation with `v1.3.7`? You can install it with `tiup install dm:v1.3.7` and run with `tiup dm:v1.3.7 import xxx`.

And if you can import it successfully with `v1.3.7`, then could you share the `~/.tiup/storage/dm/clusters/<cluster-name>/meta.yaml` file of the imported cluster? (with confidential info redacted of course).

**Comment by GMHDBJD** [comment]
dm:v1.3.7 import successfully.
cat meta.yaml
```
user: tidb
dm_version: v2.0.1
topology:
  global:
    user: tidb
    ssh_port: 22
    ssh_type: builtin
    deploy_dir: /home/tidb/deploy
    data_dir: data
    log_dir: /home/tidb/deploy/log
    os: linux
    arch: amd64
  master_servers:
  - host: 172.28.0.101
    ssh_port: 22
    name: dm-172.28.0.101-8261
    port: 8261
    peer_port: 8291
    deploy_dir: /home/tidb/deploy/dm-master-8261
    data_dir: /home/tidb/deploy/dm-master-8261/data
    log_dir: /home/tidb/deploy/log
    config:
      log-level: info
    arch: amd64
    os: linux
    v1_source_path: /home/tidb/deploy/v1source
  worker_servers:
  - host: 172.28.0.111
    ssh_port: 22
    name: dm-172.28.0.111-8262
    port: 8262
    deploy_dir: /home/tidb/deploy
    data_dir: /home/tidb/deploy/data
    log_dir: /home/tidb/deploy/log
    config:
      log-level: info
    arch: amd64
    os: linux
  - host: 172.28.0.112
    ssh_port: 22
    name: dm-172.28.0.112-8262
    port: 8262
    deploy_dir: /home/tidb/deploy
    data_dir: /home/tidb/deploy/data
    log_dir: /home/tidb/deploy/log
    config:
      log-level: info
    arch: amd64
    os: linux
  monitoring_servers:
  - host: 172.28.0.121
    ssh_port: 22
    port: 9090
    deploy_dir: /home/tidb/deploy/prometheus-9090
    data_dir: /home/tidb/deploy/prometheus.data.metrics
    log_dir: /home/tidb/deploy/log
    arch: amd64
    os: linux
  grafana_servers:
  - host: 172.28.0.121
    ssh_port: 22
    port: 3000
    deploy_dir: /home/tidb/deploy/grafana-3000
    arch: amd64
    os: linux
    username: admin
    password: admin
  alertmanager_servers:
  - host: 172.28.0.121
    ssh_port: 22
    web_port: 9093
    cluster_port: 9094
    deploy_dir: /home/tidb/deploy/alertmanager-9093
    data_dir: /home/tidb/deploy/data.alertmanager
    log_dir: /home/tidb/deploy/log
    arch: amd64
    os: linux
```
