### ISSUE TITLE
--ssh none failed to execute on hosts with dns not ip

### ISSUE THREAD

**Issue by 9547** [pingcap/tiup#1286]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

 
`tiup cluster deploy c1 v4.0.4 topology.yml --ssh none`, topology looks like below:

```yml
global:
  user: tidb
  group: pingcap
  # enable_tls: true

tidb_servers:
  - host: n4

pd_servers:
  - host: n1
  - host: n2
  - host: n3
  - host: n6
  - host: n7
  - host: n8
  - host: n9
  - host: n10
  - host: n11
  - host: n12
  - host: n13
  - host: n14
  - host: n15
  - host: n16
  - host: n17
  - host: n18
  - host: n19
  - host: n20

tikv_servers:
  - host: n1
  - host: n2
  - host: n3

monitoring_servers:
  - host: n3
grafana_servers:
  - host: n3
alertmanager_servers:
  - host: n3
```

2. What did you expect to see?

Successful deployment

3. What did you see instead?

![image](https://user-images.githubusercontent.com/29431502/113750201-140b0d80-973d-11eb-9b80-29a5f4ae4e49.png)

4. What version of TiUP are you using (`tiup --version`)?

```
master
```
