### ISSUE TITLE
Tiup fails to upgrade a stopped cluster

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiup#1292]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
tiup update --self
tiup update --all
tiup --version
1.4.0 tiup
Go Version: go1.16.2
Git Ref: v1.4.0
GitHash: eb335e6ad9d0dc19d1c43db422cd409d62bc3cea

tiup cluster --version
Starting component `cluster`: /home/stn/.tiup/components/cluster/v1.4.0/tiup-cluster --version
tiup version 1.4.0 tiup
Go Version: go1.16.2
Git Ref: v1.4.0
GitHash: eb335e6ad9d0dc19d1c43db422cd409d62bc3cea

tiup cluster deploy test-cluster v4.0.11 min.yml
tiup cluster start test-cluster
tiup cluster stop test-cluster
tiup cluster upgrade test-cluster v5.0.0-rc
...
Upgrading component pd

Error: failed to get PD leader 172.16.5.33: Get "http://172.16.5.33:12302/pd/api/v1/leader": dial tcp 172.16.5.33:12302: connect: connection refused
```

min.yml

```yml
global:
  user: "stn"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"

pd_servers:
  - host: 172.16.5.33
    client_port: 12302
    peer_port: 12303

tidb_servers:
  - host: 172.16.5.33
    port: 12304
    status_port: 12305

tikv_servers:
  - host: 172.16.5.33
    port: 12306
    status_port: 12307
```

2. What did you expect to see?

Success

3. What did you see instead?

Fail
