### ISSUE TITLE
Add `tiup cluster template --local` option

### ISSUE THREAD

**Issue by kolbe** [pingcap/tiup#1403]
## Feature Request

**Is your feature request related to a problem? Please describe:**

It would be good to have a bridge between `tiup playground` and `tiup cluster`. 
**Describe the feature you'd like:**

I'd like `tiup cluster template --local` to output a really simple cluster topology template that contains all the relevant sections, brief descriptions of each of them, and all components deployed in single-host configurations to 127.0.0.1.

Ideally, tiup would use the *current username* for global.user, and global.deploy_dir and global.data_dir that are subdirectories of the user's TIUP_HOME. 

For example:

```
global:
  user: "ubuntu"
  ssh_port: 22
  deploy_dir: "/home/ubuntu/.tiup/cluster/tidb-deploy"
  data_dir: "/home/ubuntu/.tiup/cluster/tidb-data"

pd_servers:
  - host: 127.0.0.1

tidb_servers:
  - host: 127.0.0.1

tikv_servers:
  - host: 127.0.0.1

tiflash_servers:
  - host: 127.0.0.1

monitoring_servers:
  - host: 127.0.0.1
grafana_servers:
  - host: 127.0.0.1
```

**Why the featue is needed:**

The existing cluster configuration templates are too complicated and confusing for someone who doesn't understand the components of the cluster yet.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**
