### ISSUE TITLE
Server not started due to alertmanager failure

### ISSUE THREAD

**Issue by xpepermint** [pingcap/tiup#1537]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I followed the guide at https://docs.pingcap.com/tidb/stable/production-deployment-using-tiup. I used the simple topology (single server) file and set the public server address for the `host:`. All components started successfully, but the `alertmanager` returned an error.

```yaml
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"
server_configs: {}
pd_servers:
- host: PUBLIC_IP
tidb_servers:
- host: PUBLIC_IP
tikv_servers:
- host: PUBLIC_IP
monitoring_servers:
- host: PUBLIC_IP
grafana_servers:
- host: PUBLIC_IP
alertmanager_servers: # fails
- host: PUBLIC_IP
```

2. What did you expect to see?

All cluster components to start successfully.

3. What did you see instead?

The error of the `alertmanager` at /tidb-deploy/alertmanager-9093/log/alertmanager.log:

```
level=info ts=2021-08-28T12:44:04.536261203Z caller=main.go:140 msg="Starting Alertmanager" version="(version=0.17.0, branch=HEAD, revision=c7551cd75c414dc81df027f691e2eb21d4fd85b2)"
level=info ts=2021-08-28T12:44:04.536328631Z caller=main.go:141 build_context="(go=go1.12.4, user=root@932a86a52b76, date=20190503-09:10:07)"
level=error ts=2021-08-28T12:44:04.539124506Z caller=main.go:165 msg="unable to initialize gossip mesh" err="create memberlist: Could not set up network transport: failed to obtain an address: Failed to start TCP listener on \"3.68.95.140\" port 9094: listen tcp 3.68.95.140:9094: bind: cannot assign requested address"
```

4. What version of TiUP are you using (`tiup --version`)?

1.5.5
