### ISSUE TITLE
Tiup lost numa_node for pd when generating run_pd.sh

### ISSUE THREAD

**Issue by dbsid** [pingcap/tiup#1563]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

tiup deploy pd_server with numa_node config on Arm plateform

```
pd_servers:
- host: 10.9.20.28
  ssh_port: 22
  name: pd-10.9.20.28-22389
  client_port: 22389
  peer_port: 22390
  deploy_dir: /data2/new-tidb-deploy/pd-12379
  data_dir: /data2/new-tidb-data/pd-12379
  log_dir: /data2/new-tidb-deploy/pd-12379/log
  numa_node: "1"
  arch: arm64
  os: linux
```

2. What did you expect to see?

no "numactl --cpunodebind=1 --membind=1" in scripts/run_pd.sh

3. What did you see instead?
tiup should generate run_pd.sh with numactl

```
cd "${DEPLOY_DIR}" || exit 1
exec numactl --cpunodebind=1 --membind=1 bin/pd-server \

```

4. What version of TiUP are you using (`tiup --version`)?
```
# tiup --version
1.4.4 tiup
Go Version: go1.16.4
Git Ref: v1.4.4
GitHash: 0d0507355211fe16f95e1d00ed00c39f09c7565d


```
