### ISSUE TITLE
Support automatically update the cluster name when monitoring_servers.rule_dir specified

### ISSUE THREAD

**Issue by niezefeng** [pingcap/tiup#1628]
## Feature Request

**Is your feature request related to a problem? Please describe:**
If I want to modify the Prometheus rule file, the solution is the set rule_dir that contains full *.rules.yml files.
```
monitoring_servers:
  - host: 172.16.5.134
    rule_dir: /path/to/local/rules/dir
```
The step is 
1. Copy the *rule.yaml files from Prometheus node to tiup machine.
2. Put YAML files to rule_dir, modify the YAML file.
3. Reload the Prometheus. 

I want to reuse the modified rule in all the tiup managed clusters.  Unfortunately, after specifying the rule_dir in another cluster named 'tidb-primary`, I find the tiup didn't change the labels.env.  

```
 - alert: PD_etcd_write_disk_latency
    expr: histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[1m])) by (instance,job,le) ) > 1
    for: 1m
    labels:
      env: tidb-test
      level: critical
      expr:  histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[1m])) by (instance,job,le) ) > 1
    annotations:
      description: 'cluster: tidb-test, instance: {{ $labels.instance }}, values:{{ $value }}'
      value: '{{ $value }}'
      summary: PD_etcd_write_disk_latency
```

**Describe the feature you'd like:**
To manage a modified *rule.yaml for different clusters, I want tiup can automatically update the cluster name when reload/deploy the cluster with `rule_dir` sepcified. 
And it maybe the same situation for grafana and alertmanager. 

**Why the featue is needed:**
Easier to maintain prometheus rules for multiple clusters.
