### ISSUE TITLE
Compatible with all dir paths of TiKV

### ISSUE THREAD

**Issue by HunDunDM** [pingcap/tiup#1667]
## Feature Request

**Is your feature request related to a problem? Please describe:**

If I customize `dir` in TiKV's config, there will be data remaining after `scale-in` and `prune`. When the same config is used again for `scale-out`, an error will be reported.

```
tikv_servers:
  - host: 10.0.1.5
    ssh_port: 22
    port: 20160
    status_port: 20180
    deploy_dir: /data1/deploy/tikv-20160
    data_dir: /data1/data/tikv-20160
    log_dir: /data1/log/tikv-20160
    config:
        raftstore.raftdb-path: /data2/data/tikv-20160
```

**Describe the feature you'd like:**

* all dirs path is not allowed outside of `tikv_servers[i].data_dir`.
* OR the `prune` operation will clean up these extra dirs.
* OR the `prune` operation will prompt the user to clean up these extra dirs.

These are the configs that need attention

* `--data-dir`
* `storage.data-dir`
* `raftstore.raftdb-path`
* `rocksdb.wal-dir`
* `rocksdb.info-log-dir`
* `rocksdb.titan.dirname`
* `raftdb.wal-dir`
* etc

**Why the featue is needed:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**
