### ISSUE TITLE
`--initial-commit-ts` is not assigned the correct default value

### ISSUE THREAD

**Issue by glkappe** [pingcap/tiup#1677]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

scale out drainer
```
drainer_servers: 
- host: 1055.1605.171.822
  ssh_port: 2123
  port: 82x9xx
  deploy_dir: /data/drainer-8212319/deploy
  data_dir: /data/drainer-8212319/data
  log_dir: /data/logs/drainer-8212319
  config: 
    syncer.db-type: mysql
    syncer.safe-mode: true
    syncer.to.host: 10123.112312334
    syncer.to.password: asdasd
    syncer.to.port: 3301239
    syncer.to.user: r123
    syncer.worker-count: 512
    syncer.txn-batch: 100
```

2. What did you expect to see?
cat run_drainer.sh

```
    --initial-commit-ts="-1" 2>> "/home/tidb/qh_new/deploy/drainer-3307/log/drainer_stderr.log"
```

3. What did you see instead?
    --initial-commit-ts="0" 2>> "/home/tidb/qh_new/deploy/drainer-3307/log/drainer_stderr.log"

4. What version of TiUP are you using (`tiup --version`)?
v1.8.0
