### ISSUE TITLE
cluster:  scale-out topology cannot inherit the global configuration

### ISSUE THREAD

**Issue by srstack** [pingcap/tiup#1697]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

When there is global config in the scale-out topology, although it will be prompted to ignore the global config, it is actually inherited by hosts.

2. What did you expect to see?

scale-out topology
```
global:
  deploy_dir: "/data/home/tidb-deploy"
tidb_servers:
  - host: 172.16.7.191
```
mate.yaml
```
...
topology:
  global:
    deploy_dir: /home/tidb-deploy
...
```

The New tidb_server`s  deploy_dir is /home/tidb-deploy/tidb-4000

3. What did you see instead?

The New tidb_server`s  deploy_dir is /data/home/tidb-deploy/tidb-4000

4. What version of TiUP are you using (`tiup --version`)?
1.8.1
