### ISSUE TITLE
Cluster: check for NgPort doesn't work

### ISSUE THREAD

**Issue by zhongzc** [pingcap/tiup#1726]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Run cluster with topo:
```
global:
  user: "tidb"
  deploy_dir: "/tiup/deploy"
  data_dir: "/tiup/data"

pd_servers:
  - host: pd-peer
    client_port: 2379
    peer_port: 2380

tidb_servers:
  - host: tidb-peer
    port: 4000
    status_port: 10080

tikv_servers:
  - host: tikv-peer
    port: 20160
    status_port: 20180

monitoring_servers:
  - host: tiup-peer
    port: 9090
    ng_port: -1
```

2. What did you expect to see?
 disable ngm

3. What did you see instead?
```
Failed to parse topology file: `monitoring_servers` of ng_port=-1 is invalid, port should be in the range [1, 65535]
```

4. What version of TiUP are you using (`tiup --version`)?
```
1.7.0 tiup
Go Version: go1.17.3
Git Ref: v1.7.0
GitHash: ce8eb0a645cc3ead96a44d67b1ecd5034d112cf0
```
