### ISSUE TITLE
Missing architecture check in "tiup cluster check"

### ISSUE THREAD

**Issue by dveeden** [pingcap/tiup#1741]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

With a `topology.yaml` like this:
```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"
  arch: "amd64"

...
```
Running the check against ARM64 based machines should flag that `amd64 != arm64`.

4. What version of TiUP are you using (`tiup --version`)?

```
1.8.2 tiup
Go Version: go1.17.5
Git Ref: v1.8.2
GitHash: a2912cf0470d651ce724e6c4e79871ec772abe38
```
