### ISSUE TITLE
dmctl failed to connect master with localhost after v1.9.0

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tiup#1797]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
tiup dm:v1.9.0 deploy dmcluster v5.4.0 ./topology.yaml
```
```
# The global variables apply to all other components in the configuration. If one specific value is missing in the component instance, the corresponding global variable serves as the default value.
global:
  user: "root"
  ssh_port: 22

master_servers:
  - host: 172.16.5.38
    port: 8261
    config:
      log-level: debug
worker_servers:
  - host: 172.16.5.38
    port: 8262
```

2. What did you expect to see?
```
tiup dmctl:v5.4.0 --master-addr=127.0.0.1:8261
Starting component `dmctl`: /nvme1n1/gmhdbjd/.tiup/components/dmctl/v5.4.0/dmctl/dmctl /nvme1n1/gmhdbjd/.tiup/components/dmctl/v5.4.0/dmctl/dmctl --master-addr=127.0.0.1:8261
» exit
```

3. What did you see instead?
```
Starting component `dmctl`: /nvme1n1/gmhdbjd/.tiup/components/dmctl/v5.4.0/dmctl/dmctl /nvme1n1/gmhdbjd/.tiup/components/dmctl/v5.4.0/dmctl/dmctl --master-addr=127.0.0.1:8261
Error: [code=48001:class=dmctl:scope=internal:level=high], Message: can't connect to 127.0.0.1:8261, RawCause: context deadline exceeded, Workaround: Please check your network connection.
```

with tiup dm:v1.8.2, above topo.yaml will generate dm-master config with
```
master-addr = "0.0.0.0:8261"
advertise-addr = "172.16.5.38:8261"
```
with tiup dm:v1.9.2, it generate dm-master config with
```
master-addr = "172.16.5.38:8261"
advertise-addr = "172.16.5.38:8261"
```
