### ISSUE TITLE
Tiup will report error when setting up a cluster with tikv labels which not included in location-labels

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tiup#1884]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

For the below configurations

```
tiup cluster deploy tidb-test v6.0.0 /tmp/topology.yaml --user root -i ~/.ssh/id_ed25519
```

The `/tmp/topology.yaml` content:

```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"
server_configs: {}
pd_servers:
  - host: 10.0.1.4
tidb_servers:
  - host: 10.0.1.7
tikv_servers:
  - host: 10.0.1.1
    config:
      server.labels: { region: "US" }
```

2. What did you expect to see?

User want to use placement in sql feature which does not require `isolation_labels` to be configured in PD. So no error should occur.

3. What did you see instead?

Error occurs

```
Error: check TiKV label failed, please fix that before continue:
10.0.1.1:20160:
	label name 'region' is not specified in pd config (replication.location-labels: [])
```

4. What version of TiUP are you using (`tiup --version`)?

```
1.9.4 tiup
Go Version: go1.17.8
Git Ref: v1.9.4
GitHash: 21178655f26240da5227b64988e066586a4ea6b6
```
