### ISSUE TITLE
tiup cluster edit-config: add wrong configure to tiflash-learner.toml

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [pingcap/tiup#1975]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Add some configure by `server.storages`tiup cluster edit-config xxx.
```
config:
    storage.main.dir:
    - /data1/xx/xxx/tiflash-xxx
    storage.main.capacity:
    - 53870912000
```

Then
```
[storage.main]
capacity = [536870912000]
dir = ["/data1/xxx/xxx/tiflash-xxx"]
```
will added into `tiflash-learner.toml` which is not configure of tiflash-learner.

2. What did you expect to see?

nothing be added into `tiflash-learner.toml`

3. What did you see instead?

```
[storage.main]
capacity = [536870912000]
dir = ["/data1/xxx/xxx/tiflash-xxx"]
```
was added into it.

4. What version of TiUP are you using (`tiup --version`)?
1.10.1 tiup
Go Version: go1.18.2
Git Ref: v1.10.1
GitHash: e52c3bb95644f0081c235db60d7aed9144015824
