### ISSUE TITLE
tiup-cluster: arg `--advertise-status-addr` with tikv is missing when deploying a cluster of nightly version

### ISSUE THREAD

**Issue by zhongzc** [pingcap/tiup#1988]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

original issue: https://github.com/tikv/tikv/issues/12867

1. What did you do?
deploy a cluster with topo.yaml:
```
global:
  user: "zhongzc"
  deploy_dir: "/home/zhongzc/tmp/deploy"
  data_dir: "/home/zhongzc/tmp/data"
  # enable_tls: true

pd_servers:
  - host: vm
    client_port: 2379
    peer_port: 2380

tidb_servers:
  - host: vm
    port: 4000
    status_port: 10080

tikv_servers:
  - host: vm
    port: 20160
    status_port: 20180
```

2. What did you expect to see?
```sh
❯ ps aux | grep tikv-server
zhongzc   139445  2.9  7.7 2588080 1276064 ?     Ssl  08:49   0:15 bin/tikv-server --addr 0.0.0.0:20160 --advertise-addr vm:20160 --status-addr 0.0.0.0:20180 --advertise-status-addr vm:20180 --pd vm:2379 --data-dir /home/zhongzc/tmp/data/tikv-20160 --config conf/tikv.toml --log-file /home/zhongzc/tmp/deploy/tikv-20160/log/tikv.log
```

3. What did you see instead?
```sh
❯ ps aux | grep tikv-server
zhongzc   139445  2.9  7.7 2588080 1276064 ?     Ssl  08:49   0:15 bin/tikv-server --addr 0.0.0.0:20160 --advertise-addr vm:20160 --status-addr 0.0.0.0:20180 --pd vm:2379 --data-dir /home/zhongzc/tmp/data/tikv-20160 --config conf/tikv.toml --log-file /home/zhongzc/tmp/deploy/tikv-20160/log/tikv.log
```

`--advertise-addr vm:20160` is missing.

4. What version of TiUP are you using (`tiup --version`)?
```sh
❯ tiup cluster --version
tiup-cluster version 1.9.6 tiup
Go Version: go1.17.10
Git Ref: v1.9.6
GitHash: 28965259aecd0a10ae72b69fc59121f6b4edd276
```
