### ISSUE TITLE
`tiup cluster start <cluster_name>` output shows success, but no TiKV process runs on the designated nodes

### ISSUE THREAD

**Issue by stainedatom** [pingcap/tiup#2204]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Step 1 - Use the following `topology.yaml`:
```
global:
  user: "tikv"
  ssh_port: 22
  deploy_dir: "/tikv-deploy"
  data_dir: "/tikv-data"
pd_servers:
  - host: 192.168.151.250
  - host: 192.168.133.47
  - host: 192.168.172.40
tikv_servers:
  - host: 192.168.173.212
  - host: 192.168.131.50
  - host: 192.168.131.101
monitoring_servers:
  - host: 192.168.202.125
grafana_servers:
  - host: 192.168.202.125
```

Step 2 - Run `tiup cluster check ./topology.yaml --apply --user root` and observe that one Fail persists: **service irqbalance is not running**.

Step 3 - Run `tiup cluster deploy tikv v6.5.2 ./topology.yaml --user root`, followed by `tiup cluster start tikv`. Observe the following in the output:
```
Starting component tikv
	Starting instance 192.168.131.101:20160
	Starting instance 192.168.173.212:20160
	Starting instance 192.168.131.50:20160
	Start instance 192.168.131.50:20160 success
	Start instance 192.168.173.212:20160 success
	Start instance 192.168.131.101:20160 success
```

3. What did you expect to see?

When running `tiup cluster display tikv`, we expect to see:

```
192.168.131.101:20160  tikv        192.168.131.101  20160/20180  linux/x86_64  Up    /tikv-data/tikv-20160       /tikv-deploy/tikv-20160
192.168.131.50:20160   tikv        192.168.131.50   20160/20180  linux/x86_64  Up    /tikv-data/tikv-20160       /tikv-deploy/tikv-20160
192.168.173.212:20160  tikv        192.168.173.212  20160/20180  linux/x86_64  Up    /tikv-data/tikv-20160       /tikv-deploy/tikv-20160
```

and in the nodes themselves, expect to see non-empty output upon running `sudo lsof -i:20160`.

4. What did you see instead?

```
192.168.131.101:20160  tikv        192.168.131.101  20160/20180  linux/x86_64  Down    /tikv-data/tikv-20160       /tikv-deploy/tikv-20160
192.168.131.50:20160   tikv        192.168.131.50   20160/20180  linux/x86_64  Down    /tikv-data/tikv-20160       /tikv-deploy/tikv-20160
192.168.173.212:20160  tikv        192.168.173.212  20160/20180  linux/x86_64  Down    /tikv-data/tikv-20160       /tikv-deploy/tikv-20160
```

and in the nodes themselves, an empty output upon running `sudo lsof -i:20160`.

5. What version of TiUP are you using (`tiup --version`)?

1.12.1
