### ISSUE TITLE
TiFlash numa node does not work

### ISSUE THREAD

**Issue by gengliqi** [pingcap/tiup#2384]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
tiflash_servers:
- host: 127.0.0.1
  ssh_port: 22
  patched: true
  tcp_port: 9000
  http_port: 8000
  flash_service_port: 3930
  flash_proxy_port: 20170
  flash_proxy_status_port: 20292
  metrics_port: 8234
  deploy_dir: /data1/gengliqi/tidb/deploy/tiflash-9000
  data_dir: /data1/gengliqi/tidb/data/tiflash-9000
  log_dir: /data1/gengliqi/tidb/deploy/tiflash-9000/log
  numa_node: "0"
  arch: amd64
  os: linux
```

2. What did you expect to see?
`numactl` should exist in `run_tiflash.sh`

3. What did you see instead?
```
exec bin/tiflash/tiflash server \
```

4. What version of TiUP are you using (`tiup --version`)?
1.14.0

This bug has been around for a long time. Also see https://asktug.com/t/topic/1005526, the same bug.
