### ISSUE TITLE
tiup cluster check raises `Amazon Linux 2023.5.20240903  not supported, use version 2 please`

### ISSUE THREAD

**Issue by yahonda** [pingcap/tiup#2459]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
- Startup EC2 instance using Amazon Linux 2023
```
[ec2-user@ip-10-0-18-12 ~]$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023.5.20240903"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/amazon-linux-2023/"
DOCUMENTATION_URL="https://docs.aws.amazon.com/linux/"
SUPPORT_URL="https://aws.amazon.com/premiumsupport/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
VENDOR_NAME="AWS"
VENDOR_URL="https://aws.amazon.com/"
SUPPORT_END="2028-03-15"
[ec2-user@ip-10-0-18-12 ~]$
```
- Install tiup
```
$ curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5152k  100 5152k    0     0  19.3M      0 --:--:-- --:--:-- --:--:-- 19.4M
WARN: adding root certificate via internet: https://tiup-mirrors.pingcap.com/root.json
You can revoke this by remove /home/ec2-user/.tiup/bin/7b8e153f2e2d0928.root.json
Successfully set mirror to https://tiup-mirrors.pingcap.com
Detected shell: bash
Shell profile:  /home/ec2-user/.bash_profile
/home/ec2-user/.bash_profile has been modified to add tiup to PATH
open a new terminal or source /home/ec2-user/.bash_profile to use it
Installed path: /home/ec2-user/.tiup/bin/tiup
===============================================
Have a try:     tiup playground
===============================================
[ec2-user@ip-10-0-18-12 ~]$ exec $SHELL -l
[ec2-user@ip-10-0-18-12 ~]$ which tiup
~/.tiup/bin/tiup
```
- Create topology.yml 
```
[ec2-user@ip-10-0-18-12 ~]$ tiup cluster template --local --user `whoami` --pd-servers=127.0.0.1 --tidb-servers=127.0.0.1 --tikv-servers=127.0.0.1 --monitoring-servers=127.0.0.1 --grafana-servers=127.0.0.1 > topology.yaml
[ec2-user@ip-10-0-18-12 ~]$ more topology.yaml
# For more information about the format of the tiup cluster topology file, consult
# https://docs.pingcap.com/tidb/stable/production-deployment-using-tiup#step-3-initialize-cluster-topology-file

# # Global variables are applied to all deployments and used as the default value of
# # the deployments if a specific deployment value is missing.
global:
  # # The OS user who runs the tidb cluster.
  user: "ec2-user"
  # # systemd_mode is used to select whether to use sudo permissions.
  systemd_mode: "system"
  # # SSH port of servers in the managed cluster.
  ssh_port: 22
  # # Storage directory for cluster deployment files, startup scripts, and configuration files.
  deploy_dir: "/tidb-deploy"
  # # TiDB Cluster data storage directory
  data_dir: "/tidb-data"
  # # Supported values: "amd64", "arm64" (default: "amd64")
  arch: "amd64"

pd_servers:
  - host: 127.0.0.1

tidb_servers:
  - host: 127.0.0.1

tikv_servers:
  - host: 127.0.0.1

monitoring_servers:
  - host: 127.0.0.1

grafana_servers:
  - host: 127.0.0.1


[ec2-user@ip-10-0-18-12 ~]$
```
- Run `tiup cluster check ./topology.yaml`

2. What did you expect to see?
It should say Amazon Linux 2023 is supported as documented at https://docs.pingcap.com/tidb/stable/hardware-and-software-requirements#os-and-platform-requirements as "For the following combinations of operating systems and CPU architectures, TiDB provides enterprise-level production quality,"
>  Amazon Linux 2023 | x86_64ARM 64

This documentation change has been made via https://github.com/pingcap/docs/pull/17782

3. What did you see instead?
It raises `Amazon Linux 2023.5.20240903  not supported, use version 2 please`
```
[ec2-user@ip-10-0-18-12 ~]$ tiup cluster check ./topology.yaml

+ Detect CPU Arch Name
  - Detecting node 127.0.0.1 Arch info ... Done

+ Detect CPU OS Name
  - Detecting node 127.0.0.1 OS info ... Done
+ Download necessary tools
  - Downloading check tools for linux/amd64 ... Done
+ Collect basic system information
+ Collect basic system information
  - Getting system info of 127.0.0.1:22 ... Done
+ Check time zone
  - Checking node 127.0.0.1 ... Done
+ Check system requirements
+ Check system requirements
+ Check system requirements
+ Check system requirements
  - Checking node 127.0.0.1 ... Done
  - Checking node 127.0.0.1 ... Done
  - Checking node 127.0.0.1 ... Done
  - Checking node 127.0.0.1 ... Done
  - Checking node 127.0.0.1 ... Done
  - Checking node 127.0.0.1 ... Done
+ Cleanup check files
  - Cleanup check files on 127.0.0.1:22 ... Done
Node       Check         Result  Message
----       -----         ------  -------
127.0.0.1  thp           Fail    THP is enabled, please disable it for best performance
127.0.0.1  cpu-governor  Warn    Unable to determine current CPU frequency governor policy
127.0.0.1  limits        Fail    soft limit of 'nofile' for user 'ec2-user' is not set or too low
127.0.0.1  limits        Fail    hard limit of 'nofile' for user 'ec2-user' is not set or too low
127.0.0.1  limits        Fail    soft limit of 'stack' for user 'ec2-user' is not set or too low
127.0.0.1  memory        Pass    memory size is 1024MB
127.0.0.1  sysctl        Fail    net.core.somaxconn = 4096, should be greater than 32768
127.0.0.1  sysctl        Fail    net.ipv4.tcp_syncookies = 1, should be 0
127.0.0.1  sysctl        Fail    vm.swappiness = 60, should be 0
127.0.0.1  selinux       Pass    SELinux is disabled
127.0.0.1  service       Fail    service irqbalance is not running
127.0.0.1  service       Pass    service firewalld not found, ignore
127.0.0.1  command       Fail    numactl not usable, bash: line 1: numactl: command not found
127.0.0.1  os-version    Fail    Amazon Linux 2023.5.20240903  not supported, use version 2 please
127.0.0.1  cpu-cores     Pass    number of CPU cores / threads: 1
[ec2-user@ip-10-0-18-12 ~]$
```

5. What version of TiUP are you using (`tiup --version`)?
