### ISSUE TITLE
Default log_dir '/home/{user}' for monitored is not quite good.

### ISSUE THREAD

**Issue by lizhenda** [pingcap/tiup#325]
My topology yaml is as follow. Then the log dir for blackbox_exporter/node_exporter will be set to '/home/tidb'.  I think '{deploy_dir}/monitor-xxx/logs' for the default log dir here will be a better choice.

```
# Tip: PD priority needs to be manually set using the PD-ctl client tool. such as, member Leader_priority PD-name numbers.
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/data/tidb/"
  #data_dir: ""
  #log_dir: ""
#monitored:
#  node_exporter_port: 9100
#  blackbox_exporter_port: 9115
#  deploy_dir: ""
#  data_dir: ""
#  log_dir: ""
```
