### ISSUE TITLE
pd-server config not work

### ISSUE THREAD

**Issue by jiashiwen** [pingcap/tiup#435]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
i want to config pd-server to accsess from public ip.
topo.yml 
```
pd_servers:
 - host: 10.0.1.110
   config:
     client-urls: "http://0.0.0.0:2379" 
     peer-urls: "http://0.0.0.0:2380" 
     advertise-client-urls: "http://114.67.122.185:2379"
     advertise-peer-urls: "http://114.67.122.185:2380"

```

but ps -ef|grep pd-server the result is
```
idb      6425     1  2 16:49 ?        00:00:14 bin/pd-server --name=pd-10.0.1.110-2379 --client-urls=http://10.0.1.110:2379 --advertise-client-urls=http://10.0.1.110:2379 --peer-urls=http://10.0.1.110:2380 --advertise-peer-urls=http://10.0.1.110:2380 --data-dir=/tidb-data/pd-2379 --initial-cluster=pd-10.0.1.110-2379=http://10.0.1.110:2380 --config=conf/pd.toml --log-file=/tidb-deploy/pd-2379/log/pd.log

```

the config not in operation

2. What did you expect to see?
--advertise-peer-urls=http://10.0.1.110:2380
 --advertise-client-urls=http://10.0.1.110:2379 
shoud be
--advertise-peer-urls=http://114.67.122.185:2380
--advertise-client-urls=http://114.67.122.185:2379 

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?
