### ISSUE TITLE
tiup cluster upgrade --force` may break consistency

### ISSUE THREAD

**Issue by lucklove** [pingcap/tiup#566]
Provide the `test.yaml` in `/tmp/test`:
```yaml
global:
  user: test
  deploy_dir: "tidb-deploy"
  data_dir: "tidb-data"

tidb_servers:
  - host: 172.16.5.140

pd_servers:
  - host: 172.16.5.140

tikv_servers:
  - host: 172.16.5.140
```

And the `test.sh` in `/tmp/test`:
```sh
#! /bin/sh

tiup cluster deploy test v4.0.0 /tmp/test/test.yaml -y
tiup cluster start test
tiup cluster stop test
tiup cluster upgrade test v4.0.1 --force
```

The upgrade action will fail at starting tikv
