### ISSUE TITLE
Support config global server params in topology.yaml

### ISSUE THREAD

**Issue by lucklove** [pingcap/tiup#571]
example:
```yaml
tidb_servers:
   port: 4000
   status_port: 10080
   deploy_dir: "/tidb-deploy/tidb-4000"
   log_dir: "/tidb-deploy/tidb-4000/log"
  - host: 172.16.5.140
  - host: 172.16.5.139
     log_dir: xxxx

pd_servers:
  - host: 172.16.5.140

tikv_servers:
  - host: 172.16.5.140
```

**Comment by lonng** [comment]
We cannot accomplish this way, we must add a global field for it.

**Comment by lucklove** [comment]
> We cannot accomplish this way, we must add a global field for it.

Why? Isn't this way more graceful?

**Comment by lonng** [comment]
😭 It's invalid yaml syntax.

**Comment by lucklove** [comment]
> 😭 It's invalid yaml syntax.

Oh, my fault

**Comment by lucklove** [comment]
I believe we can solve this problem by [YAML anchors](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/):

```yaml
tidb_spec: &tidb_spec
  port: 3306
  deploy_dir: "test-deploy"
  log_dir: "test-deploy/log"

tidb_servers:
  - <<: *tidb_spec
    host: 172.0.0.1
  - <<: *tidb_spec
    host: 172.0.0.2
  - host: 172.0.0.3  # this host will not inherit tidb_spec
```

This will be expanded as:

```yaml
--- 
tidb_servers: 
  - 
    deploy_dir: test-deploy
    host: "172.0.0.1"
    log_dir: test-deploy/log
    port: 3306
  - 
    deploy_dir: test-deploy
    host: "172.0.0.2"
    log_dir: test-deploy/log
    port: 3306
  - 
    host: "172.0.0.3"

tidb_spec: 
  deploy_dir: test-deploy
  log_dir: test-deploy/log
  port: 3306
```
