### ISSUE TITLE
Wrong dir names of node_exporter after import from ansible

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiup#613]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

* deploy a cluster
* import from ansible using tiup cluster import

configure in `inventory.ini`
```
# node_exporter and blackbox_exporter servers
[monitored_servers]
172.16.5.81
172.16.5.59
172.16.5.85
```

2. What did you expect to see?
After reload or upgrade, the config file of node_exporter/blackbox_exporter is the same as the origin one.

3. What did you see instead?
```
monitored:
  node_exporter_port: 9100
  blackbox_exporter_port: 9115
  deploy_dir: deploy/monitor-9100
  data_dir: data/monitor-9100
  log_dir: deploy/monitor-9100/log
```
The `deply_dir`/`data_dir`/`log_dir` is not correct.

4. What version of TiUP are you using (`tiup --version`)?
1.0.8
