### ISSUE TITLE
Destroy Command Does Not Clean TiFlash Data Directories

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tiup#865]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Use `tiup cluster destroy` command to destroy a cluster with TiFlash
```
tiflash_servers:
  - host: 172.16.5.81
    tcp_port: 5020
    http_port: 5030
    flash_service_port: 7333
    flash_proxy_port: 13170
    flash_proxy_status_port: 13292
    metrics_port: 12234
    data_dir: "/home/tidb/birdstorm/data1,/home/tidb/birdstorm/data3"
    config:
      capacity: "10737418240,10737418240"
      logger:
        level: info
```

2. What did you expect to see?
TiFlash data directories should be deleted

3. What did you see instead?
```
+ [ Serial ] - DestroyCluster
Destroying component tiflash
Destroying instance 172.16.5.81
Deleting paths on 172.16.5.81: /home/tidb/birdstorm/deploy/tiflash-5020/log /home/tidb/birdstorm/deploy/tiflash-5020 /etc/systemd/system/tiflash-5020.service
Destroy 172.16.5.81 success
- Destroy tiflash paths: [/home/tidb/birdstorm/deploy/tiflash-5020/log /home/tidb/birdstorm/deploy/tiflash-5020 /etc/systemd/system/tiflash-5020.service]
```

4. What version of TiUP are you using (`tiup --version`)?
v1.2.1
