### ISSUE TITLE
 dm: scale-out didn't handle prometheus version correctlly

### ISSUE THREAD

**Issue by lucklove** [pingcap/tiup#876]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

topo.yaml:
```yaml
master_servers:
  - host: 172.16.5.140
  - host: 172.16.5.139
  - host: 172.16.5.134
worker_servers:
  - host: 172.16.5.140
  - host: 172.16.5.139
  - host: 172.16.5.134
```

scale.yaml
```yaml
monitoring_servers:
  - host: 172.16.5.139

grafana_servers:
  - host: 172.16.5.139
```
2. What did you expect to see?
I have prometheus and grafana finally

3. What did you see instead?
```sh
Error: failed to scp /root/.tiup/storage/dm/packages/dm-master-v4.0.3-linux-amd64.tar.gz to root@172.16.5.181:/tidb/dm/deploy/grafana-3000/_tiup_tmp/dm-master-v4.0.3-linux-amd64.tar.gz: open /root/.tiup/storage/dm/packages/dm-master-v4.0.3-linux-amd64.tar.gz: no such file or directory

Verbose debug logs has been written to /root/logs/tiup-cluster-debug-2020-11-02-15-06-48.log.
```

4. What version of TiUP are you using (`tiup --version`)?

v1.2.3
