### ISSUE TITLE
`log_dir` for `drainer_servers` doesn't take effect?

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/tiup#895]
## General Question

Before asking a question, make sure you have:

- Searched existing Stack Overflow questions.
- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/pingcap/tiup/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [TiUP Readme](https://github.com/pingcap/tiup)
  - [TiUP Doc](https://github.com/pingcap/docs)

**Comment by 9547** [comment]
Try to reproduce, could you please paste the deployed topo YAML file.

**Comment by 9547** [comment]
@csuzhangxc Sorry, but I can't reproduce the issue you meet, and My topo as below:

```yaml
...
drainer_servers:
  - host: 172.19.0.103
    data_dir: /home/tidb/data/drainer-8249/data
    log_dir: /home/tidb/log/drainer-8249

```

Could you please explain in detail the steps of your operation, and print-out the topology
