### ISSUE TITLE
Add Syntax Checking After 'tiup cluster edit-config' 

### ISSUE THREAD

**Issue by xinghua0123** [pingcap/tiup#995]
After changing the cluster config using 'tiup cluster edit-config', the command line is showing config changes successfully even though I have a typo inside.

For example I have following in config:
```
tikv_servers:
- host: 172.16.4.194
  ssh_port: 22
  imported: true
  port: 20160
  status_port: 20180
  deploy_dir: /data1/deploy
  data_dir: /data1/deploy/data
  log_dir: /data1/deploy/log
  config:
    server.lables:  # TYPO！！！！
      host: host2
  arch: amd64
  os: linux
```

It will be great if there is a feature to check the config syntax which helps to faster troubleshoot.
